
# server config
appName: "app2"
version: "1.0.0"
clientType: "PC_WEB"
title: "microFrontend-1"
serverPort: 6002
logLevel: "INFO"
logDist: "d:\\log/app2"
# bff keep-alive超时时间
# keepAliveTimeout: 60000
# backend socket超时时间
socketTimeout: 60000
# 文件处理超时时间
fileSocketTimeout: 180000
# 加密编码
encoding: "base64"

# dev
# client
dev_clientPort: 4002
dev_publicPath: ""
dev_apiPath: "https://focusapi.vemic.com/mock/209"
# server
dev_domainUrl: "http://app2.paludina.dev.com"
dev_mainAppDomainUrl: "http://paludina.dev.com"
dev_backendUrl: "https://focusapi.vemic.com/mock/209"

# prod
# client
publicPath: "dist/"
apiPath: "https://focusapi.vemic.com/mock/209"
# server
domainUrl: "https://app2.paludina.prod.com"
mainAppDomainUrl: "https://paludina.prod.com"
backendUrl: "https://focusapi.vemic.com/mock/209"

# cdn 地址
cdn: ""
